### ISSUE TITLE
Uncaught ReferenceError: SpinnerDialog is not defined

### ISSUE THREAD

**Issue by gotoark** [Paldom/SpinnerDialog#45]
SpinnerDialog Works Perfectly but while come back to the previous Activity it throws Uncaught ReferenceError: SpinnerDialog is not defined.

**Comment by AgNm** [comment]
Add setTimeout while calling it , its taking time in loading. I also faced same issue.

**Comment by fredchung1224** [comment]
Try window.plugins.spinnerDialog.show();
