### ISSUE TITLE
npm package is not alligned to github source code

### ISSUE THREAD

**Issue by MacondoExpress** [Paldom/SpinnerDialog#50]
Package npm 1.3.1 doesn't contain commit c89c418555b2df55bf5697df7f4f662641fa0af1 that fix transparent dialog on Android.

**Comment by greybax** [comment]
you can use fork https://github.com/greybax/cordova-plugin-native-spinner which contains all fixes from this parent repo

**Comment by MacondoExpress** [comment]
Thanks!
